name:                brigid
version:             0.3.0.0
github:              "AugmenTab/brigid"
license:             BSD-3-Clause
author:              "Tyler Baum"
maintainer:          "tyler.baum@protonmail.com"
copyright:           "2023 Tyler Baum"

language: Haskell2010

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AugmenTab/brigid#readme>

default-extensions:
- ImportQualifiedPost
- OverloadedStrings

dependencies:
- base
- beeline-http-client
- beeline-routing
- bytestring
- constraints
- containers
- crypton
- extra
- foldable1-classes-compat
- hashable
- hedgehog
- html-email-validate
- http-types
- integer-types
- iso3166-country-codes
- json-fleece-aeson
- json-fleece-core
- libphonenumber
- memory
- mtl
- non-empty-text
- ogma
- scientific
- semigroupoids
- shrubbery
- text
- time
- validation

ghc-options:
- -j
- -Werror
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-orphans

library:
  source-dirs: src
  exposed-modules:
    - Brigid.Examples.HTML
    - Brigid.Examples.HXML
    - Brigid.HTML.Analysis
    - Brigid.HTML.Attributes
    - Brigid.HTML.Elements
    - Brigid.HTML.Elements.Safe
    - Brigid.HTML.Elements.SVG
    - Brigid.HTML.Entities
    - Brigid.HTML.Generation
    - Brigid.HTML.Generation.Attributes
    - Brigid.HTML.Generation.Elements
    - Brigid.HTML.HTMX.Config
    - Brigid.HTML.Render.ByteString
    - Brigid.HTML.Render.String
    - Brigid.HTML.Render.Text
    - Brigid.HTML.Types
    - Brigid.HXML.Attributes
    - Brigid.HXML.Elements
    - Brigid.HXML.Entities
    - Brigid.HXML.Render.ByteString
    - Brigid.HXML.Render.String
    - Brigid.HXML.Render.Text
    - Brigid.HXML.Types
    - Brigid.Types

tests:
  brigid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brigid
      - hedgehog
      - tasty
      - tasty-hedgehog

benchmarks:
  brigid-bench:
    main:        Bench.hs
    source-dirs: bench
    ghc-options:
      - -fproc-alignment=64
      - -threaded
      - -rtsopts
      - -with-rtsopts "-N -T -A32m"
    dependencies:
      - blaze-html
      - brigid
      - lucid
      - tasty-bench
