#!/bin/bash

set -e

source scripts/lib/run-in-container.sh

echo "=============================="
echo "====== Building  Brigid ======"
echo "=============================="

stack build --fast --test --bench "$@"
