#!/bin/bash

echo "===================================="
echo "====== Fetching HTML Entities ======"
echo "===================================="

docker compose --file compose.entities.yml up --abort-on-container-exit

