module HTML.Elements.TagType
  ( TagType
      ( Document
      , Comment
      , Text
      , RawHTML
      , Anchor
      , Abbreviation
      , ContactAddress
      , Area
      , Article
      , Aside
      , Audio
      , BringAttentionTo
      , Base
      , BidirectionalIsolation
      , BidirectionalOverride
      , Blockquote
      , Body
      , LineBreak
      , Button
      , Canvas
      , TableCaption
      , Citation
      , Code
      , TableColumn
      , TableColumnGroup
      , Data
      , DataList
      , DescriptionDetails
      , DeletedText
      , Details
      , Definition
      , Dialog
      , Division
      , DescriptionList
      , DescriptionTerm
      , Emphasis
      , Embed
      , Fieldset
      , FigureCaption
      , Figure
      , Footer
      , Form
      , H1
      , H2
      , H3
      , H4
      , H5
      , H6
      , Head
      , Header
      , HeadingGroup
      , HorizontalRule
      , Html
      , IdiomaticText
      , IFrame
      , Image
      , Input
      , InsertedText
      , KeyboardInput
      , Label
      , Legend
      , ListItem
      , Link
      , Main
      , Map
      , Mark
      , Menu
      , Meta
      , Meter
      , Nav
      , NoScript
      , Object
      , OrderedList
      , OptionGroup
      , Option
      , Output
      , Paragraph
      , Picture
      , PreformattedText
      , Progress
      , Quotation
      , RubyParenthesis
      , RubyText
      , Ruby
      , Strikethrough
      , Sample
      , Script
      , Search
      , Section
      , Select
      , Slot
      , SideComment
      , Source
      , Span
      , Strong
      , Style
      , Subscript
      , Summary
      , Superscript
      , Table
      , TableBody
      , TableDataCell
      , ContentTemplate
      , TextArea
      , TableFoot
      , TableHeader
      , TableHead
      , Time
      , Title
      , TableRow
      , Track
      , Underline
      , UnorderedList
      , Variable
      , Video
      , WordBreakOpportunity
      )
  ) where

data TagType
  = Document
  | Comment
  | Text
  | RawHTML
  | Anchor
  | Abbreviation
  | ContactAddress
  | Area
  | Article
  | Aside
  | Audio
  | BringAttentionTo
  | Base
  | BidirectionalIsolation
  | BidirectionalOverride
  | Blockquote
  | Body
  | LineBreak
  | Button
  | Canvas
  | TableCaption
  | Citation
  | Code
  | TableColumn
  | TableColumnGroup
  | Data
  | DataList
  | DescriptionDetails
  | DeletedText
  | Details
  | Definition
  | Dialog
  | Division
  | DescriptionList
  | DescriptionTerm
  | Emphasis
  | Embed
  | Fieldset
  | FigureCaption
  | Figure
  | Footer
  | Form
  | H1
  | H2
  | H3
  | H4
  | H5
  | H6
  | Head
  | Header
  | HeadingGroup
  | HorizontalRule
  | Html
  | IdiomaticText
  | IFrame
  | Image
  | Input
  | InsertedText
  | KeyboardInput
  | Label
  | Legend
  | ListItem
  | Link
  | Main
  | Map
  | Mark
  | Menu
  | Meta
  | Meter
  | Nav
  | NoScript
  | Object
  | OrderedList
  | OptionGroup
  | Option
  | Output
  | Paragraph
  | Picture
  | PreformattedText
  | Progress
  | Quotation
  | RubyParenthesis
  | RubyText
  | Ruby
  | Strikethrough
  | Sample
  | Script
  | Search
  | Section
  | Select
  | Slot
  | SideComment
  | Source
  | Span
  | Strong
  | Style
  | Subscript
  | Summary
  | Superscript
  | Table
  | TableBody
  | TableDataCell
  | ContentTemplate
  | TextArea
  | TableFoot
  | TableHeader
  | TableHead
  | Time
  | Title
  | TableRow
  | Track
  | Underline
  | UnorderedList
  | Variable
  | Video
  | WordBreakOpportunity
